import { assertPaise, PAISE_PER_RUPEE, type Paise } from './money.js';

/** One CSV cell: text, a whole number, or empty. */
export type CsvCell = string | number | null;

/** Characters that make a spreadsheet read a cell as a formula (CSV injection). */
const FORMULA_START = /^[=+\-@\t\r]/;

/** A plain decimal number such as "-0.40" (a negative amount, not a formula). */
const PLAIN_NUMBER = /^-?\d+(\.\d+)?$/;

/**
 * One cell, quoted when it holds a comma, quote or line break (RFC 4180). Text that a spreadsheet
 * would run as a formula (a staff name or item typed as "=HYPERLINK(...)") gets a leading
 * apostrophe, so an exported report can never execute anything when opened (RPT-017, SEC).
 * Numbers, and text that is just a number such as "-0.40", are written as they are.
 */
export function csvCell(value: CsvCell): string {
  if (value === null) return '';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new TypeError('A CSV number must be finite');
    return String(value);
  }
  const text = FORMULA_START.test(value) && !PLAIN_NUMBER.test(value) ? `'${value}` : value;
  return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

/** Rows as CSV text with CRLF line ends and a trailing line end (RFC 4180). */
export function toCsv(rows: readonly (readonly CsvCell[])[]): string {
  return rows.map((row) => row.map(csvCell).join(',')).join('\r\n') + '\r\n';
}

/**
 * Paise as a plain rupee amount for spreadsheets: "1234.50", "-0.40". No symbol and no digit
 * grouping, so the column sums as numbers; the amount is exact (integer arithmetic).
 */
export function csvRupees(amount: Paise): string {
  assertPaise(amount, 'amount', true);
  const absolute = Math.abs(amount);
  const rupees = Math.trunc(absolute / PAISE_PER_RUPEE);
  const paise = absolute % PAISE_PER_RUPEE;
  return `${amount < 0 ? '-' : ''}${String(rupees)}.${String(paise).padStart(2, '0')}`;
}

/** The heading block every export starts with (RPT-017): what, for whom, filters, by and when. */
export interface CsvStamp {
  readonly title: string;
  readonly restaurant: string;
  readonly filters: readonly (readonly [label: string, value: string])[];
  readonly generatedBy: string;
  /** Already in the restaurant's local time, e.g. "26-09-2026 13:05 IST". */
  readonly generatedAt: string;
}

/** A named table inside an export (a report can have several, e.g. items and categories). */
export interface CsvSection {
  readonly heading?: string;
  readonly columns: readonly string[];
  readonly rows: readonly (readonly CsvCell[])[];
}

/** A whole export: the stamp, a blank line, then each section separated by a blank line. */
export function stampedCsv(stamp: CsvStamp, sections: readonly CsvSection[]): string {
  const rows: CsvCell[][] = [
    [stamp.title],
    ['Restaurant', stamp.restaurant],
    ...stamp.filters.map(([label, value]) => [label, value]),
    ['Generated by', stamp.generatedBy],
    ['Generated at', stamp.generatedAt],
  ];
  for (const section of sections) {
    rows.push([]);
    if (section.heading !== undefined) rows.push([section.heading]);
    rows.push([...section.columns]);
    for (const row of section.rows) {
      if (row.length !== section.columns.length) {
        throw new TypeError(
          `A row has ${String(row.length)} cells; the section has ${String(section.columns.length)} columns`,
        );
      }
      rows.push([...row]);
    }
  }
  return toCsv(rows);
}
