import { describe, expect, it } from 'vitest';
import { csvCell, csvRupees, stampedCsv, toCsv } from '../src/index.js';

describe('[RPT-017] CSV export', () => {
  it('quotes cells with commas, quotes and line breaks (RFC 4180)', () => {
    expect(csvCell('Paneer Tikka')).toBe('Paneer Tikka');
    expect(csvCell('Tikka, half')).toBe('"Tikka, half"');
    expect(csvCell('6" naan')).toBe('"6"" naan"');
    expect(csvCell('two\nlines')).toBe('"two\nlines"');
    expect(csvCell(null)).toBe('');
    expect(csvCell(-400)).toBe('-400');
    expect(() => csvCell(Number.NaN)).toThrow(TypeError);
  });

  it('neutralises text a spreadsheet would run as a formula', () => {
    expect(csvCell('=HYPERLINK("x")')).toBe(`"'=HYPERLINK(""x"")"`);
    expect(csvCell('+91 98')).toBe("'+91 98");
    expect(csvCell('-cash')).toBe("'-cash");
    expect(csvCell('@sum')).toBe("'@sum");
    expect(csvCell('\tx')).toBe("'\tx");
    expect(csvCell('-0.40')).toBe('-0.40');
    expect(csvCell('-1+1')).toBe("'-1+1");
  });

  it('joins rows with CRLF and ends with a line end', () => {
    expect(
      toCsv([
        ['a', 1],
        [null, 'b'],
      ]),
    ).toBe('a,1\r\n,b\r\n');
  });

  it('writes paise as plain rupees that sum as numbers', () => {
    expect(csvRupees(123_456_78)).toBe('123456.78');
    expect(csvRupees(5)).toBe('0.05');
    expect(csvRupees(-40)).toBe('-0.40');
    expect(csvRupees(0)).toBe('0.00');
    expect(() => csvRupees(1.5)).toThrow();
  });

  it('stamps the export with restaurant, filters, generated by and at', () => {
    const csv = stampedCsv(
      {
        title: 'Sales summary',
        restaurant: 'Spice Route',
        filters: [
          ['From', '2026-09-01'],
          ['To', '2026-09-26'],
        ],
        generatedBy: 'Asha',
        generatedAt: '26-09-2026 13:05 IST',
      },
      [
        { columns: ['Date', 'Net'], rows: [['2026-09-01', '100.00']] },
        { heading: 'By hour', columns: ['Hour'], rows: [[13]] },
      ],
    );
    expect(csv.split('\r\n')).toEqual([
      'Sales summary',
      'Restaurant,Spice Route',
      'From,2026-09-01',
      'To,2026-09-26',
      'Generated by,Asha',
      'Generated at,26-09-2026 13:05 IST',
      '',
      'Date,Net',
      '2026-09-01,100.00',
      '',
      'By hour',
      'Hour',
      '13',
      '',
    ]);
  });

  it('refuses a row that does not match its columns', () => {
    const stamp = {
      title: 'T',
      restaurant: 'R',
      filters: [],
      generatedBy: 'A',
      generatedAt: 'now',
    };
    expect(() => stampedCsv(stamp, [{ columns: ['a', 'b'], rows: [['x']] }])).toThrow(TypeError);
  });
});
