import {
  LICENSE_STATES,
  ORDER_ITEM_STATES,
  ORDER_SOURCES,
  ROLES,
  SERVICE_REQUEST_STATES,
  SERVICE_REQUEST_TYPES,
  TABLE_STATES,
} from '@rp/domain';
import { z } from 'zod';

/**
 * Entity ids are UUIDs (UUIDv7 recommended: time-ordered, generated by clients offline; ADR-0005).
 */
export const Id = z.uuid();
export type Id = z.infer<typeof Id>;

/** Client-generated unique id on every submission (ORD-013). */
export const IdempotencyKey = z.uuid();

/** Money in integer paise (BRD §9.4). */
export const Paise = z.int().nonnegative();
/** Money that may be negative, e.g. a round-off adjustment. */
export const SignedPaise = z.int();
/** Rates in basis points: 250 = 2.5 %. */
export const BasisPoints = z.int().nonnegative().max(10_000);

export const IsoDate = z.iso.date();
/** Instants are ISO-8601 in UTC (NFR-L03); clients display them in IST. */
export const Timestamp = z.iso.datetime({ offset: false });

export const Role = z.enum(ROLES);
export const OrderSource = z.enum(ORDER_SOURCES);
export const OrderItemState = z.enum(ORDER_ITEM_STATES);
export const TableState = z.enum(TABLE_STATES);
export const ServiceRequestType = z.enum(SERVICE_REQUEST_TYPES);
export const ServiceRequestState = z.enum(SERVICE_REQUEST_STATES);
export const LicenseState = z.enum(LICENSE_STATES);

export const OrderType = z.enum(['DINE_IN', 'TAKEAWAY']);
export const FoodType = z.enum(['VEG', 'NON_VEG', 'EGG']);
export const PriceMode = z.enum(['TAX_EXCLUSIVE', 'TAX_INCLUSIVE']);
export const PaymentMode = z.enum(['CASH', 'CARD', 'UPI', 'OTHER']);
/** Ordering surfaces an item can be visible on (MENU-002). */
export const SalesChannel = z.enum(['POS', 'WAITER_APP', 'TABLE_TABLET', 'QR']);
export const DeviceType = z.enum([
  'POS',
  'KDS',
  'WAITER_PHONE',
  'TABLE_TABLET',
  'PAGER',
  'MANAGER_BROWSER',
]);

/** Optional mapping to another POS or aggregator system (INT-005). */
export const ExternalId = z.string().min(1).max(128).optional();

/** Error body returned by every API (NFR-U04: plain-language message plus a stable code). */
export const ApiError = z.object({
  code: z.string().min(1),
  message: z.string().min(1),
  details: z.record(z.string(), z.unknown()).optional(),
  correlationId: z.string().optional(),
});
export type ApiError = z.infer<typeof ApiError>;
