#!/usr/bin/env node
// Requirement traceability (BRD §18.3): every Must requirement must be linked to at least one
// passing test. Tests reference requirements by putting the ID in square brackets in a
// describe/it title, e.g. `it('[BILL-003] never reuses invoice numbers', ...)`.
//
// Usage:
//   pnpm trace            writes docs/build/TRACEABILITY.md and prints a summary
//   pnpm trace --strict   also exits 1 if any Must requirement has no test (pilot gate, P8)
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const strict = process.argv.includes('--strict');
const catalog = JSON.parse(readFileSync(join(root, 'docs', 'brd', 'requirements.json'), 'utf8'));
const known = new Map(catalog.requirements.map((requirement) => [requirement.id, requirement]));

const SKIP_DIRS = new Set([
  'node_modules',
  'dist',
  'coverage',
  '.turbo',
  '.git',
  '.next',
  '.expo',
  'build',
]);
const TEST_FILE = /\.(test|spec|e2e)\.(ts|tsx|js|mjs)$/;
const REFERENCE = /\[((?:[A-Z]{2,4})-\d{3}|NFR-[A-Z]\d{2})\]/g;

function* walk(directory) {
  for (const entry of readdirSync(directory)) {
    if (SKIP_DIRS.has(entry)) continue;
    const path = join(directory, entry);
    if (statSync(path).isDirectory()) yield* walk(path);
    else if (TEST_FILE.test(entry)) yield path;
  }
}

const coverage = new Map();
const unknown = new Map();
for (const directory of ['apps', 'packages', 'firmware', 'tests']) {
  let files;
  try {
    files = [...walk(join(root, directory))];
  } catch {
    continue;
  }
  for (const file of files) {
    const content = readFileSync(file, 'utf8');
    for (const match of content.matchAll(REFERENCE)) {
      const id = match[1];
      const target = known.has(id) ? coverage : unknown;
      if (!target.has(id)) target.set(id, new Set());
      target.get(id).add(relative(root, file));
    }
  }
}

const byPriority = {
  M: { total: 0, covered: 0 },
  S: { total: 0, covered: 0 },
  C: { total: 0, covered: 0 },
};
const uncoveredMust = [];
for (const requirement of catalog.requirements) {
  const bucket = byPriority[requirement.priority];
  bucket.total += 1;
  if (coverage.has(requirement.id)) bucket.covered += 1;
  else if (requirement.priority === 'M') uncoveredMust.push(requirement);
}

const lines = [
  '# Requirement traceability',
  '',
  'Generated by `pnpm trace`. Do not edit by hand. A requirement counts as covered when at least',
  'one test title contains its ID in square brackets, e.g. `[BILL-003]`.',
  '',
  `Must: ${byPriority.M.covered} / ${byPriority.M.total} covered. Should: ${byPriority.S.covered} / ${byPriority.S.total}. Could: ${byPriority.C.covered} / ${byPriority.C.total}.`,
  '',
  '## Covered requirements',
  '',
];
for (const requirement of catalog.requirements) {
  const files = coverage.get(requirement.id);
  if (files)
    lines.push(`- ${requirement.id} (${requirement.priority}): ${[...files].sort().join(', ')}`);
}
lines.push('', '## Must requirements without a test', '');
let lastArea = '';
for (const requirement of uncoveredMust) {
  if (requirement.area !== lastArea) {
    if (lines.at(-1) !== '') lines.push('');
    lines.push(`### ${requirement.area}`, '');
    lastArea = requirement.area;
  }
  lines.push(
    `- ${requirement.id}: ${requirement.text.slice(0, 110)}${requirement.text.length > 110 ? '…' : ''}`,
  );
}
if (unknown.size > 0) {
  lines.push('', '## References to unknown requirement IDs (fix these)', '');
  for (const [id, files] of unknown) lines.push(`- ${id}: ${[...files].sort().join(', ')}`);
}
// Format with Prettier so the generated file always passes `pnpm format:check` in CI.
const outputPath = join(root, 'docs', 'build', 'TRACEABILITY.md');
const prettierOptions = (await prettier.resolveConfig(outputPath)) ?? {};
writeFileSync(
  outputPath,
  await prettier.format(`${lines.join('\n')}\n`, { ...prettierOptions, parser: 'markdown' }),
);

process.stdout.write(
  `Traceability: Must ${byPriority.M.covered}/${byPriority.M.total}, Should ${byPriority.S.covered}/${byPriority.S.total}, Could ${byPriority.C.covered}/${byPriority.C.total}.\n`,
);
if (unknown.size > 0) {
  process.stdout.write(
    `Unknown requirement IDs referenced in tests: ${[...unknown.keys()].join(', ')}\n`,
  );
  process.exitCode = 1;
}
if (strict && uncoveredMust.length > 0) {
  process.stdout.write(`${uncoveredMust.length} Must requirements have no test.\n`);
  process.exitCode = 1;
}
