import { describe, expect, it } from 'vitest';
import {
  accentVariables,
  buildTokensCss,
  colorVariables,
  cssVar,
  cssVarName,
  spacing,
  staticVariables,
  THEME_NAMES,
  themes,
  themeVariables,
} from '../src/index.js';

describe('[NFR-U01] tokens as CSS variables', () => {
  it('names variables in kebab-case under the rp prefix', () => {
    expect(cssVarName('color', 'surfaceRaised')).toBe('--rp-color-surface-raised');
    expect(cssVarName('font-size', '2xl')).toBe('--rp-font-size-2xl');
    expect(cssVar('space', 4)).toBe('var(--rp-space-4)');
  });

  it('emits one colour variable per role with the TS value', () => {
    for (const theme of THEME_NAMES) {
      const variables = colorVariables(theme);
      expect(Object.keys(variables)).toHaveLength(Object.keys(themes[theme]).length);
      expect(variables['--rp-color-background']).toBe(themes[theme].background);
      expect(variables['--rp-color-on-primary']).toBe(themes[theme].onPrimary);
    }
  });

  it('emits spacing in px, font sizes in rem and the default touch target', () => {
    const variables = staticVariables();
    expect(variables['--rp-space-4']).toBe(`${String(spacing[4])}px`);
    expect(variables['--rp-font-size-md']).toBe('1rem');
    expect(variables['--rp-touch-target']).toBe('48px');
    expect(variables['--rp-duration-normal']).toBe('200ms');
  });

  it('[KDS-011] raises type size and touch target in the KDS theme only', () => {
    expect(themeVariables('kds')['--rp-touch-target']).toBe('64px');
    expect(themeVariables('kds')['--rp-font-size-md']).toBe('1.25rem');
    expect(themeVariables('light')['--rp-touch-target']).toBeUndefined();
    expect(themeVariables('dark')['--rp-font-size-md']).toBeUndefined();
  });

  it('builds a layered stylesheet with every theme, OS dark mode and reduced motion', () => {
    const css = buildTokensCss();
    expect(css).toMatch(/^\/\* Generated by @rp\/design-tokens/);
    expect(css).toContain('@layer rp.tokens {');
    for (const theme of THEME_NAMES) expect(css).toContain(`[data-theme='${theme}'] {`);
    expect(css).toContain('@media (prefers-color-scheme: dark)');
    expect(css).toContain(':root:not([data-theme])');
    expect(css).toMatch(
      /prefers-reduced-motion: reduce\) \{\s+:root \{\s+--rp-duration-instant: 0ms;/,
    );
    expect(css).toContain('color-scheme: dark;');
    expect(css).toContain(`--rp-color-background: ${themes.kds.background};`);
    // Balanced braces: a quick guard against malformed output.
    expect(css.split('{').length).toBe(css.split('}').length);
  });
});

describe('[NFR-U02] restaurant accent colour', () => {
  it('sets the accent and a readable text colour on it', () => {
    expect(accentVariables('#fde047')).toEqual({
      '--rp-color-accent': '#fde047',
      '--rp-color-on-accent': '#000000',
    });
    expect(accentVariables('#7c2d12')['--rp-color-on-accent']).toBe('#ffffff');
  });

  it('rejects values that are not hex colours, so branding data cannot inject CSS', () => {
    expect(() => accentVariables('red; background: url(x)')).toThrow(RangeError);
  });
});
