import * as prettier from 'prettier';
import { stringify } from 'yaml';
import type { RouteDefinition } from '../../src/routes.js';
import { buildAsyncApi } from './asyncapi.js';
import { buildOpenApi } from './openapi.js';
import type { z } from 'zod';

export interface RenderOptions {
  namespace: Readonly<Record<string, unknown>>;
  routes: readonly RouteDefinition[];
  events: z.ZodDiscriminatedUnion;
  version: string;
  /** Directory the files are written to; Prettier resolves its config from here. */
  outDir: string;
}

export interface RenderedFile {
  name: string;
  content: string;
}

/** Renders docs/api/openapi.json and docs/api/asyncapi.yaml, formatted as Prettier would. */
export async function renderDocs(options: RenderOptions): Promise<RenderedFile[]> {
  const openapi = buildOpenApi(options);
  const asyncapi = buildAsyncApi(options);
  return [
    {
      name: 'openapi.json',
      content: await format(JSON.stringify(openapi), `${options.outDir}/openapi.json`),
    },
    {
      name: 'asyncapi.yaml',
      content: await format(
        '# Generated by `pnpm contracts:docs` from @rp/contracts. Do not edit by hand.\n' +
          stringify(asyncapi, { lineWidth: 0, aliasDuplicateObjects: false }),
        `${options.outDir}/asyncapi.yaml`,
      ),
    },
  ];
}

async function format(source: string, filepath: string): Promise<string> {
  const config = await prettier.resolveConfig(filepath);
  return prettier.format(source, { ...config, filepath });
}
